[theme]
base = "dark"                 # Options: "light" or "dark"
primaryColor = "#00BFFF"      # Accent color (buttons, sliders, etc.)
backgroundColor = "#040818"   # App background
secondaryBackgroundColor = "#383a3d"  # Sidebar and widgets
textColor = "#FAFAFA"         # Text color
font = "serif"           # Options: "sans serif", "serif", "monospace"
